name: run tests

on:
  pull_request:
  push:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    #----------------------------------------------
    #              install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: uv sync

    #----------------------------------------------
    #              run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        uv run coverage run -m pytest
        uv run coverage report --fail-under=60
